### ISSUE TITLE
Breaks view bobbing

### ISSUE THREAD

**Issue by kevinthegreat1** [0x3C50/Renderer#21]
This breaks the default view shake with the view bobbing setting turned on. I see that there is code to prevent view bobbing in [GameRendererMixin](https://github.com/0x3C50/Renderer/blob/master/src/main/java/me/x150/renderer/mixin/GameRendererMixin.java), and I'm wondering what is it fixing?

I got the bug report from [here](https://github.com/kevinthegreat1/SkyblockMod-Fabric/issues/6).

**Comment by 0x3C50** [comment]
How is it breaking? I can't reproduce any issue as of now.

The fix for view bobbing prevents the rendered elements swaying with the hand, that's all it does.

**Comment by 0x3C50** [comment]
I tested a bit more and did notice a slight issue, but I wouldn't call it "breaking" vanilla view bobbing. The rendered content didn't sway at all, which seems to be caused by a code change in the vanilla renderer that broke the existing code that was supposed to fix it. I need more context to figure out what exactly is "breaking" here tho.

**Comment by saefty-git** [comment]
Demonstration of the bug (first clip expected behavior, second clip with Renderer):
[https://streamable.com/qx8mmp](https://streamable.com/qx8mmp)

There are other mods used in the video but the exact same issue occurs when using only the latest Fabric 1.19.4 and Renderer with no extras.

In the meantime I will test the fix.

**Comment by 0x3C50** [comment]
> Demonstration of the bug (first clip expected behavior, second clip with Renderer): https://streamable.com/qx8mmp
> 
> There are other mods used in the video but the exact same issue occurs when using only the latest Fabric 1.19.4 and Renderer with no extras.
> 
> In the meantime I will test the fix.

Weird, that didn't happen when I tested it. Something probably got desynced, which messed with the setting update the old mixin did. The mentioned fix should work for this, since it doesn't modify any settings anymore.

**Comment by saefty-git** [comment]
The fix worked, thanks.
