### ISSUE TITLE
[Suggestion] Font Glyph Fallback

### ISSUE THREAD

**Issue by bruh1273** [0x3C50/Renderer#49]
Using the FontRenderer with a custom font has one downside. The pack typically doesn't have all supported glyphs.
My suggestion: If the glyph map doesn't contain a specific glyph, use the DEFAULT Minecraft FontRenderer's glyph map to find a fallback glyph.

**Comment by 0x3C50** [comment]
add another widely used font behind your custom font. that's what that's made for. if the first font doesnt contain the glyph, the second one is searched. if the second one doesnt have it, the third is searched, etc.

**Comment by bruh1273** [comment]
Why make the user add in so much effort just for a task to be done automatically? The MC font has standard support for many needs.

**Comment by 0x3C50** [comment]
because the user might not want an entirely different predefined glyph to take the place of their placeholder symbol. it's better to respond with the default "i don't know what this glyph is, please fix it" rather than use some pixelated, entirely out of line glyph from the default font. if they'd want that to happen, they would use the vanilla font renderer

for niche glyphs, i don't see the use anyway. if they want that glyph specifically to draw, they would use their own font. if they want that text to be drawn in the vanilla style, they would use the vanilla font renderer
