### ISSUE TITLE
World Rendering utiltities

### ISSUE THREAD

**Issue by mineblock11** [0x3C50/Renderer#9]
Methods that allow you to pass in a matrices, world, blockpos, direction ect. and it renders that section of the world for you?

**Comment by 0x3C50** [comment]
I forgot to comment on this, but I responded to you on discord about it already. I feel like an entire rendering system based around purely world rendering would be a bit out of scope for this project, since it's designed to only provide the building blocks to get rendering working. Maybe I'll do something like that in the future, but its not really planned right now.
